; This file was auto-generated by drush_make
core = 7.x

api = 2
projects[] = "drupal"
; Modules
projects[] = "addressfield"
projects[] = "admin"
projects[] = "ctools"
projects[] = "commerce"
projects[] = "commerce_paypal"
projects[] = "date"
projects[] = "entity"
projects[] = "rules"
projects[] = "views"
; Themes
projects[] = "omega"